### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by psiotwo** [ZFIN/zebrafish-anatomical-ontology#165]
Two pairs of OWL classes share the same definition.

First pair:
[ZFA:0000807](http://purl.obolibrary.org/obo/ZFA_0000807)
[ZFA:0000927](http://purl.obolibrary.org/obo/ZFA_0000927)

Second pair:
[ZFA:0000944](http://purl.obolibrary.org/obo/ZFA_0000944)
[ZFA:0005112](http://purl.obolibrary.org/obo/ZFA_0005112)

**Comment by cerivs** [comment]
This will be fixed in the next release

**Comment by matentzn** [comment]
```
ERROR	duplicate_label	larva	rdfs:label	larva
ERROR	duplicate_label	larva	rdfs:label	larva
ERROR	duplicate_label	juvenile	rdfs:label	juvenile
ERROR	duplicate_label	juvenile	rdfs:label	juvenile
ERROR	duplicate_label	adult	rdfs:label	adult
ERROR	duplicate_label	adult	rdfs:label	adult
```

Still some duplicate labels:

@cerivs if you want to really get rid of these, you need to rename the `obsolete` classes as `obsolete`.

For example, `larva` should be labelled `obsolete larva` to avoid name conflicts.

**Comment by cerivs** [comment]
@matentzn Is his is a new change to policy about naming classes?  These were not previously a problem.

**Comment by matentzn** [comment]
No, these were always a in OBO principles, see https://obofoundry.org/principles/fp-012-naming-conventions.html: having to classes with the same name. There is no 100% rule on how to deal with obsolete class names - some people delete the labels, other just prepend the prefix "obsolete", like in "obsolete larva" to indicate to users that the term is, indeed, obsolete.

**Comment by cerivs** [comment]
Will be in the next release.
