### ISSUE TITLE
NTR: DC2 dopaminergic neuron, NTR:DC4 dopaminergic neuron

### ISSUE THREAD

**Issue by LeylaR** [ZFIN/zebrafish-anatomical-ontology#170]
## Preferred term label

DC2 dopaminergic neuron
DC4 dopaminergic neuron

## Synonyms

(e.g., Absent spleen)

## Textual definition

Group of diencephalic dopaminergic neurons that ascend from the posterior tuberculum to the subpallium. These neurons may be the correlate of mammalian substantia nigra (SNc) neurons. DC2 and DC4 neurons are large and pear-shaped. 
PMID:33731451
PMID:21266970
PMID:12128258
PMID:11166725

## Suggested parent term
dopaminergic neuron

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by LeylaR** [comment]
## References
Ilin, V.A., Bai, Q., Watson, A.M., Volgushev, M., Burton, E.A. (2021) Mechanism of pacemaker activity in zebrafish DC2/4 dopaminergic neurons. The Journal of neuroscience : the official journal of the Society for Neuroscience. 41(18):4141-4157.
PMID:33731451
ZFIN PUB ID:ZDB-PUB-210319-11

From the abstract of Ilin et al. 2021:
“The ascending dopaminergic projection from the posterior tuberculum (diencephalic populations DC2 and DC4) to the subpallium is considered the zebrafish correlate of the mammalian nigrostriatal projection, but little is known about the neurophysiology of zebrafish DC2/4 neurons.”
"Posterior tuberculum DC2/4 dopaminergic neurons are considered the zebrafish correlate of mammalian substantia nigra (SNc) neurons, whose degeneration causes the motor signs of Parkinson's disease (PD). Our study shows that DC2/4 and SNc neurons share a number of electrophysiological properties - including depolarized membrane potential, high input resistance, and continual, cell-autonomous pacemaker activity - that strengthen the basis for the increasing use of zebrafish models to study the molecular pathogenesis of PD."
________
Extensive detail and information on additional DC and other neuron types can be found in this publication which shows “at cellular resolution the complete set of projections (‘projectome’) of every single type of DA and noradrenergio neurons in the central nervous system of zebrafish larvae”. See especially Figures 5, 6 and 7 for details on DC2 and DC4 neurons.
Tay, T.L., Ronneberger, O., Ryu, S., Nitschke, R., and Driever, W. (2011) Comprehensive catecholaminergic projectome analysis reveals single-neuron integration of zebrafish ascending and descending dopaminergic systems. Nature communications. 2:171.
PMID:21266970
ZFIN PUB ID:ZDB-PUB-110131-27
________
Rink and Wullimann refer to the neurons as “populations 2 and 4” and describe them as “large pear-shaped neurons displaying obvious branched neurites”. The neurons are detected in adult zebrafish and were also detected in 2 and 5 d zebrafish
Rink, E. and Wullimann, M.F. (2002) Development of the catecholaminergic system in the early zebrafish brain: an immunohistochemical study. Brain research. Developmental brain research. 137(1):89-100.
PMID:12128258
ZFIN PUB ID:ZDB-PUB-020730-6
_________
“The posterior tubercular catecholaminergic cells include three cytological types (small round, large pear-shaped, and bipolar liquor-contacting cells). Furthermore, the retrograde neuronal tracers DiI or biocytin were applied to demonstrate ascending projections to the basal telencephalon (incl. the striatum)”
Rink, E. and Wullimann, M.F. (2001) The teleostean (zebrafish) dopaminergic system ascending to the subpallium (striatum) is located in the basal diencephalon (posterior tuberculum). Brain research. 889:316-330. 
PMID:11166725
ZFIN PUB ID:  ZDB-PUB-001220-2

**Comment by cerivs** [comment]
Will be in next release
