### ISSUE TITLE
NTR: neuromast-associated ionocyte

### ISSUE THREAD

**Issue by LeylaR** [ZFIN/zebrafish-anatomical-ontology#171]
## Preferred term label

neuromast-associated ionocyte

## Synonyms

Nm ionocyte

## Textual definition

Ionocytes associated with neuromasts. Nm ionocytes are not present at the time of neuromast deposition, and are derived from basal keratinocytes surrounding neuromasts. Nm ionocyte progenitors migrate into neuromasts as pairs of cells. The invasion process is triggered in response to changing environmental stimuli such as salinity and pH. (PMID 33878346).

## Suggested parent term

ionocyte

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by cerivs** [comment]
Will be in next release
