### ISSUE TITLE
NTR: motor exit point glia

### ISSUE THREAD

**Issue by LeylaR** [ZFIN/zebrafish-anatomical-ontology#172]
## Preferred term label

motor exit point glia

## Synonyms

MEP glia

## Textual definition
A type of glial cell that restricts CNS-residing myelinating glia from entering the PNS. MEP glia “originate from within the CNS, then migrate into the PNS, divide and produce cells that ensheath and myelinate spinal motor root axons.”
PMID: 25268888
PMID: 30356886

## Suggested parent term

glial cell (sensu Vertebrata)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by cerivs** [comment]
ZDB-PUB-141001-1 =PMID: 25268888
ZDB-PUB-181026-18= PMID: 30356886

**Comment by cerivs** [comment]
Will be in the next release.
