### ISSUE TITLE
NTR: pseudobranch

### ISSUE THREAD

**Issue by LeylaR** [ZFIN/zebrafish-anatomical-ontology#176]
## Preferred term label

pseudobranch

## Textual definition

An epithelial structure located anterior to the gill filaments and connected to the eye via the ophthalmic artery. It arises from mandibular arch neural crest-derived mesenchyme and first pouch endodermal epithelia. The pseudobranch appears as a small bud behind the eye at 4dpf. At 17 dpf, the pseudobranch is composed of five distinct filaments that resemble the primary gill filaments, with the five filaments merging to form a single pseudobranch by adult stages (90 dpf).  
The pseudobranch may regulate ocular blood pressure and/or have an endocrine function.  (Definition derived entirely from Thiruppathy et al. 2022, PMID 35762575).

References
PubMed IDs 35762575, 18626070, 16786554, 12722101, 34048735

**Comment by LeylaR** [comment]
The original quotes from PMID 35762575 (Thiruppathy et al. 2022), from which the textual definition was derived:

"The pseudobranch is an epithelial structure located just behind the eye that has been proposed
to regulate ocular blood pressure and/or have an endocrine function (Jollie, 1962)."

"In zebrafish, the pseudobranch is located anterior to the gill filaments and connected to the eye via
the ophthalmic artery (Figure 1a, c), as described for other fishes (Laurent and Dunel- Erb, 1984). The
pseudobranch appears in histological sections as a small bud behind the eye at 4 days post-fertilization
(dpf)" (Figure 1b). Examination of Sox10:Cre; acta2:loxP- BFP- Stop- loxP- dsRed zebrafish shows this
bud to be composed of a core of Cre-converted dsRed+ neural crest-derived cells ensheathed by
unconverted BFP+ epithelia (Figure 1—figure supplement 1a). The position of this bud corresponds
to kdrl:mCherry labeling of a branch of the first aortic arch that likely gives rise to the ophthalmic
artery (Figure 1—figure supplement 1b). At 17 dpf, the pseudobranch is composed of five distinct
filaments that resemble the primary gill filaments, with the five filaments merging to form a single
pseudobranch by adult stages (90 dpf) (Figure 1b). Alcian Blue staining reveals that the adult pseudo-
branch contains five cartilage rods, reflecting the five fused filaments, with this cartilage resembling
the specialized filament cartilage seen in the gills (Figure 1d; Fabian et al., 2022)."

"The pseudobranch therefore arises from mandibular arch neural crest-derived mesenchyme and first pouch endodermal epithelia."

Images of the pseudobranch: 
from 5762575 Figure 1 https://zfin.org/ZDB-IMAGE-220629-80
from 34048735 Figure 7 https://zfin.org/ZDB-IMAGE-221001-52 


In addition to Thiruppathy et al 2022, earlier publications by Jonz and Nurse include information on the zebrafish pseudobranch:
PMID 18626070 https://zfin.org/ZDB-PUB-080722-8 (Review)
PMID 16786554 https://zfin.org/ZDB-PUB-060623-20 (see Figure 4)
PMID 12722101 https://zfin.org/ZDB-PUB-030602-9 (see Figure 1H)

From PMID 18626070 Jonz and Nurse 2008 https://zfin.org/ZDB-PUB-080722-8:
"The pseudobranch is a nonrespiratory, reduced gill-like organ that has remained an enigma since its initial discovery [see Laurent and Dunel-Erb for a historical review (Laurent and Dunel-Erb, 1984)]. While pseudobranch structure is variable between fish species, it resides within the cranial portion of the opercular epithelium, where it is not exposed to the external environment, and its primary cellular component is that of the pseudobranch cell (PBC). These cells are characterized by apical localization of the enzyme Na + /K + -ATPase and an extensive cytoplasmic tubular network (Fig. 6B; Laurent and Dunel-Erb, 1984; Quinn et al., 2003; Jonz and Nurse, 2006)."

**Comment by cerivs** [comment]
Will be in the next release
