### ISSUE TITLE
Possible NTRs: striolar hair cell, extrastriolar hair cell

### ISSUE THREAD

**Issue by LeylaR** [ZFIN/zebrafish-anatomical-ontology#179]
Should striolar and extrastriolar hair cells be added to the AO?
Striolar and extrastriolar hair cells occupy distinct regions of the zebrafish macula and can be distinguished anatomically and molecularly. 

From the abstract of Shi et al. 2023 36598134:
"In the maculae, we identify two subtypes of hair cells that share gene expression with mammalian striolar or extrastriolar hair cells. In situ hybridization reveals that these hair cell subtypes occupy distinct spatial domains within the three macular organs, the utricle, saccule, and lagena, consistent with the reported distinct electrophysiological properties of hair cells within these domains."

From Shi et al. 2023:
The striola is characterized by hair cells with taller ciliary bundles and encompasses a line of polarity reversal where hair cells change their stereocilia orientation (Figure 1E).

In situ hybridization reveals that these hair cell subtypes occupy distinct spatial domains within the utricle, saccule, and lagena, and computational comparison of hair cell types reveals homology with striolar and extrastriolar hair cell types in mammals. .

References:

Shi, T., Beaulieu, M.O., Saunders, L.M., Fabian, P., Trapnell, C., Segil, N., Crump, J.G., Raible, D.W. (2023) Single-cell transcriptomic profiling of the zebrafish inner ear reveals molecularly distinct hair cell and supporting cell subtypes. eLIFE. 12:. 
https://zfin.org/ZDB-PUB-230105-1
PMID 36598134 

Smith, E.T., Sun, P., Yu, S.K., Raible, D.W., Nicolson, T. (2023) Differential expression of mechanotransduction complex genes in auditory/vestibular hair cells in zebrafish. Frontiers in molecular neuroscience. 16:12748221274822. 
https://zfin.org/ZDB-PUB-231201-8
PMID 38035267 

Liu, Z., Hildebrand, D.G.C., Morgan, J.L., Jia, Y., Slimmon, N., Bagnall, M.W. (2022) Organization of the gravity-sensing system in zebrafish. Nature communications. 13:5060. 
https://zfin.org/ZDB-PUB-220829-1
PMID 36030280

Tanimoto, M., Watakabe, I., Higashijima, S.I. (2022) Tiltable objective microscope visualizes selectivity for head motion direction and dynamics in zebrafish vestibular system. Nature communications. 13:76227622. 
https://zfin.org/ZDB-PUB-221222-10
PMID 36543769 
**"We find that head vibration is preferentially received by striolar HCs, whereas static tilt is preferentially transduced by extrastriolar HCs."**

Sun, P., Smith, E., Nicolson, T. (2023) Transmembrane channel-like (Tmc) subunits contribute to frequency sensitivity in the zebrafish utricle. The Journal of neuroscience : the official journal of the Society for Neuroscience. 44(1):. 
https://zfin.org/ZDB-PUB-231114-8
PMID 37952940

**Comment by cerivs** [comment]
Proposed definition:  @LeylaR  can you look at these and see if they look ok?
extrastriolar hair cell
Hair cell that is located in the macula and cristae surrounding the central area of polarity reversal where hair cell change their stereocilia orientation. The kinocilium and tallest stereocilium are unequal in height when the cells are mature. Extrastriolar hair cells excite predominantly regular-firing vestibular afferents with tonic or phasic-tonic dynamic.
striolar hair cell
Hair cell that is located in the macula and cristae along the central area of polarity reversal where hair cell change their stereocilia orientation. The kinocilium and tallest stereocilium are roughly equal in height when the cells are mature.  These cells carry high-pass signals which are predominantly relayed by irregular-firing vestibular afferents with phasic kinetics.

**Comment by LeylaR** [comment]
@cerivs the definitions look good, thanks.

**Comment by cerivs** [comment]
Will be in the next re
